// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5otdy9VENmQbrpToTsbyssIJLgJjWDno',
    appId: '1:538751272855:web:27675b848d50a939f7a6d2',
    messagingSenderId: '538751272855',
    projectId: 'logif-tcc',
    authDomain: 'logif-tcc.firebaseapp.com',
    storageBucket: 'logif-tcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrKUkxTekXoSGxY7OZaSGA_S8ajcPJrUY',
    appId: '1:538751272855:android:46d37abdae551f12f7a6d2',
    messagingSenderId: '538751272855',
    projectId: 'logif-tcc',
    storageBucket: 'logif-tcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKe0d8dDzJVmPWFwGOspMl-wA9q55_KA',
    appId: '1:538751272855:ios:108b34da55ee8bf7f7a6d2',
    messagingSenderId: '538751272855',
    projectId: 'logif-tcc',
    storageBucket: 'logif-tcc.appspot.com',
    androidClientId: '538751272855-ucacoatih7olh7u2fj2hhnq371qalid3.apps.googleusercontent.com',
    iosClientId: '538751272855-imimk1ud30pp5bbsq6vvi15275ak9bi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.logif',
  );
}
